---
title: "check_data"
author: "Anna"
date: "2024-06-18"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1)
```
# Vorbereitungen

```{r essentials}
# clean workspace
rm(list=ls())
packages <- c("data.table", "tidyverse", "ggplot2", "glmmTMB")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}
# Load packages
invisible(lapply(packages, library, character.only = TRUE))

# current date:
DATE <- format(Sys.Date(), "%Y%m%d")

# themes and options
options(scipen = 999)

# output folders
folder_table <- file.path("..", "output/tables")
folder_plot <- file.path("..", "output/figures")

if (!file.exists(folder_table)) {
  dir.create(folder_table, recursive = TRUE)
}

if (!file.exists(folder_plot)) {
  dir.create(folder_plot, recursive = TRUE)
}
```

# Daten Import

```{r data_import}
print(getwd())
datapath <- file.path("..", "input") #at least monthly users in GER
#read in all files in datapath 
filenames <- list.files(datapath, full.names = T)

#save all files as separate dataframes
ldf <- lapply(filenames, readRDS)
names(ldf) <- gsub(".rds", "", basename(filenames))
print(names(ldf))
names <- c("pragma_id_GKV", "diagnoses", "medications", "employment", "income", "inpat", "qwt")
names(ldf) <- names
#check if all dataframes are loaded
ls()
list2env(ldf, envir = .GlobalEnv)
rm(ldf)
```
# Daten vorbereiten

```{r recode_ENTL}
table(qwt$ENTL301)
str(qwt$ENTL301)
#QWT as factor with new labels
qwt$ENTL301 <- factor(qwt$ENTL301, levels = c(1, 2, 3, 4, 6, 7, 9, 10, 13, 14, 15, 17, 22), labels = c("regulär", "beendet, nachstat. Beh. vorgesehen", "aus sonstigen Gründen beendet", "gegen ärztlichen Rat beendet", "Verlegung in ein anderes Krankenhaus", "Tod", "Rehaeinrichtung",
"Pflegeeinrichtung", "externe Verlegung zur psychiatrischen Behandlung", "aus sonst. Gründen beend., nachstat. Beh. Vorges.", "gegen ärztlichen Rat beendet, nachstat. Beh. vorgeseh.", "interne Verlegung m. Wechsel zw. D. Gelt.b. BPflV u. KHEntgG", "Fallabschl. (int. V.) b. Wechsel zw. Voll- und teilst. Beh."))
#was passiert nach interne Verlegung m. Wechsel zw. D. Gelt.b. BPflV u. KHEntgG?
```

```{r check_data}
prop.table(table(qwt$ENTL301))
str(qwt$ENTL301)
ggplot(qwt, aes(x = ENTL301)) + geom_bar() + theme(axis.text.x = element_text(angle = 25, hjust = 1))

qwt <- qwt %>% 
  mutate(n_days = as.integer(difftime(as.Date(date.qwt.end), as.Date(date.qwt.start), units = "days")))

```
```{r}
prop.table(table(qwt$ENTL301))
str(qwt$ENTL301)
ggplot(qwt, aes(x = ENTL301)) + geom_bar() + theme(axis.text.x = element_text(angle = 25, hjust = 1))

qwt <- qwt %>% 
  filter(ENTL301 != "Tod") %>%
  mutate(unpl_drop = factor(case_when(
  ENTL301 %in% c("aus sonstigen Gründen beendet", "gegen ärztlichen Rat beendet", "gegen ärztlichen Rat beendet, nachstat. Beh. vorgeseh.") ~ 1,
  ENTL301 %in% c("regulär", "beendet, nachstat. Beh. vorgesehen", "Verlegung in ein anderes Krankenhaus", "Rehaeinrichtung", "Pflegeeinrichtung",
                 "externe Verlegung zur psychiatrischen Behandlung", "aus sonst. Gründen beend., nachstat. Beh. Vorges.", "interne Verlegung m. Wechsel zw. D. Gelt.b. BPflV u. KHEntgG", "Fallabschl. (int. V.) b. Wechsel zw. Voll- und teilst. Beh.") ~ 0,
  TRUE ~ NA_real_), levels = c(0, 1), labels = c("nein", "ja")))

prop.table(table(qwt$unpl_drop))
ggplot(qwt, aes(x = unpl_drop, y = n_days)) + geom_violin() + geom_boxplot(width = 0.1) + theme(axis.text.x = element_text(angle = 35, hjust = 1))

ENTL_ndays <- ggplot(qwt, aes(x = ENTL301, y = n_days, fill = unpl_drop)) + 
  geom_jitter(alpha=0.1, size = rel(0.8), ) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  scale_y_continuous(breaks = seq(0, 100, by = 5)) +
  #change y axis label
  ylab("Anzahl Tage in QWT") +
  xlab("Entlassungsgrund (ENTL301)") +
  #change legend title
  labs(fill = "Unplanmäßiger Behandlungsabbruch", title = "Dauer eines Qualifizierten Entzugs nach Entlassungsgrund unter GKV Versicherten", caption = "Anmerk.: Datenpunkte markieren einzelne Behandlungen") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1, size = rel(0.85))) +
  theme(legend.position = "top")
  

ENTL_ndays

ggsave(file.path(folder_plot, "ENTL_ndays.png"), ENTL_ndays, width = 10, height = 6)

```
# Hinzufügen der Stammdaten 
```{r add_stammdaten}
#match pragma_id_GKV with qwt based on pragma_id (only columns names sex and yob)
total <- left_join(qwt, pragma_id_GKV, by="pragmaid")

total <- total %>% 
  select(c(-gkv.y, -hivid, -gkv.id, -dak.id, -aok.id)) %>%
  mutate(age= as.integer(substr(date.qwt.start, 1, 4)) - yob)

total$pragmaid <- factor(total$pragmaid)


```

# Aufstellen eines Modells zur Vorhersage von unpl_drop
```{r model}
#work in progress
model <- glmmTMB(unpl_drop ~ sex + age + qwt_id + (1|pragmaid), data = total, family = binomial)
summary(model)
```

# -0.936 (Intercept) ist geschätzt als log odds für abgebrochene Behandlung bei einer Frau, die 0 Jahre alt ist und ihre erste QWT hat.
# der Koeffizient für männlich ist 0.37, was bedeutet, dass Männer eher abbrechen als Frauen.